openapi: 3.0.0
info:
  title: User Login API
  description: API for user login
  version: 1.0.0
servers:
  - url: http://localhost:8082/signup/login.jsp
paths:
  /login:
    post:
      summary: User Login
      description: Authenticate a user with the provided credentials.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's email address.
                password:
                  type: string
                  description: User's password.
              required:
                - username
                - password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the logged-in user.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Indicates login status ("failed").
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating internal server error.
