openapi: 3.0.0
info:
  title: Sign-up API
  version: 1.0.0
  description: API for user registration
servers:
  - url: http://localhost:8080  # Update with your server URL
paths:
  /register:
    post:
      summary: Register a new user
      description: Register a new user with name, email, password, and contact number
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User's name
                email:
                  type: string
                  format: email
                  description: User's email address
                pass:
                  type: string
                  description: User's password
                contact:
                  type: string
                  description: User's contact number
              required:
                - name
                - email
                - pass
                - contact
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Registration status (success/failed)
        '400':
          description: Invalid request data
        '500':
          description: Internal server error
