openapi: 3.0.0
info:
  title: User Information API
  description: API to retrieve user information
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
paths:
  /user/{userId}:
    get:
      summary: Get User Information
      description: Retrieve information about a specific user.
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve information for.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    format: int64
                    description: Unique identifier for the user.
                  username:
                    type: string
                    description: Username of the user.
                  email:
                    type: string
                    format: email
                    description: Email address of the user.
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating user was not found.
